sudo: false
language: node_js
node_js:
  - "10"
  - "8"

script: npm run test-ci
before_install:
- npm i -g npm@6
- npm i -g --production coveralls
after_script:
- cat ./coverage/lcov.info | coveralls
